---
name: Jelena
surname: Bugarin
position: "Data Analyst | mag. psych."
#address: ""
phone: 
email: ""
#twitter: 
github: podatkovni-okvir
#linkedin: 
#date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am a psychologist interested in data analysis, data science, and automation. Driven by curiosity and the need to understand how things are working, I am always ready to learn something new and switch things up in order to try and make stuff more efficient."
output: vitae::awesomecv
#csl: apa7.csl
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(tibble)
library(googlesheets4)
library(tidyr)
library(stringr)
```
<!-- avoiding highlight color in section titles -->
``` {=latex}
\setbool{acvSectionColorHighlight}{false}
```

```{r data_import}
google_sheet <- "https://docs.google.com/spreadsheets/d/1_6JCugS2G_5Qr3eRJGMqKUubcg9WKMgGe2wlTDkxo2U/edit?usp=sharing"
# link to googlesheet with data
gs4_deauth() # API for googlesheets
gs4_info <- gs4_get(google_sheet) # get sheet names
for (sheet in gs4_info$sheets$name) { # importing each sheet into separate df
    df_name <- paste("df", sheet, sep = "_")
    df <- read_sheet(google_sheet, sheet = sheet)
    gdata::mv(from = "df", to =df_name)
}
```

```{r data_prep}
df_detailed_entries <- filter(df_detailed_entries, show == TRUE) # filtering eneries I do not want to show
dfl_detailed_entries <- pivot_longer(df_detailed_entries, 
                                     cols = starts_with("description"), 
                                     values_to = "description", 
                                     values_drop_na = TRUE
                                     )  # getting data into needed format

dfl_detailed_entries[dfl_detailed_entries == "_"] <- NA
# detailed enteries without descriptions 

for (detailed_section in unique(dfl_detailed_entries$section)) {
    df_name <- paste("df", detailed_section, sep = "_")
    df <- dplyr::filter(dfl_detailed_entries, section == detailed_section)
    gdata::mv(from = "df", to =df_name)
} # creating separate df for every section



df_brief_enteries <- filter(df_brief_enteries, show == TRUE) # filtering brief enteries

for (brief_section in unique(df_brief_enteries$section)) {
    df_name <- paste("df", brief_section, sep = "_")
    df <- dplyr::filter(df_brief_enteries, section == brief_section)
    gdata::mv(from = "df", to =df_name)
} # creating separate df for every section
```

# Experience

```{r experience}
detailed_entries(df_experience, title, where, institution, when, description)
```

# Education

```{r education}
detailed_entries(df_education, title, where, institution, when, description)
```


# Volunteering

```{r volunteering}
detailed_entries(df_volunteering, title, where, institution, when, description)
```

# Projects

```{r projects}
detailed_entries(df_projects, institution, where, title, when, description)
```

\newpage 

# Certifications

```{r certifications}
# using detailed enteries on brief eneteries because I like that setup more
detailed_entries(df_certifications, what = institution, where = when, with = title)
```

# Skills

```{r skills}

detailed_entries(df_skills, what = institution, with = title)
```

# Publications and Conferences

```{r publications-and-conferences}

bibliography_entries(here::here("data", "publications-and-conferences.bib"))
```
